backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: fromdetail/eternal-tree-db
media_folder: "src/assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Characters"
    name: "character"
    identifier_field: name
    folder: "src/game-data/characters"
    create: true
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - label: "Element"
        name: "element"
        widget: "select"
        options: ["Fire", "Water", "Wind", "Earth", "Light", "Dark"]
        default: "Fire"
      - label: "Gacha Type"
        name: "gacha"
        widget: "select"
        options: ["Permanent", "Limited", "Event"]
        default: "Permanent"
      - label: "Role"
        name: "role"
        widget: "select"
        options: ["Attack", "Defense", "Special", "Support"]
        default: "Attack"
      - label: "Weapon type"
        name: "weapon"
        widget: "select"
        options: ["Sword", "Spear", "Staff", "Bow", "Dagger", "Axe"]
        default: "Sword"
      - label: "Rarity"
        name: "rarity"
        widget: "select"
        options: ["SP", "SSR", "SR", "R"]
        default: "SSR"
      - { label: "Attack", name: "attack", widget: "number", value_type: "int" }
      - { label: "Health", name: "health", widget: "number", value_type: "int" }
      - label: "Skins"
        name: "skins"
        widget: "list"
        summary: "{{fields.skin.name}}"
        default: []
        fields:
          - label: "Skin"
            name: "skin"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
      - label: "Bursts"
        name: "resonances"
        widget: "list"
        summary: "{{fields.resonance.name}}"
        default: []
        fields:
          - label: "Burst"
            name: "resonance"
            widget: "object"
            fields:
              - { label: "Burst Name", name: "name", widget: "string" }
              - { label: "Burst Icon", name: "icon", widget: "image" }
              - label: "Burst Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Burst Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Burst Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Burst Effect Name", name: "name", widget: "string", default: "wtf" }
                      - { label: "Burst Effect Description", name: "description", widget: "text" }
                      - { label: "Burst Effect Icon", name: "icon", widget: "image" }
      - label: "Skills"
        name: "skills"
        widget: "list"
        default: []
        summary: "{{fields.skill.name}}"
        fields:
          - label: "Skill"
            name: "skill"
            widget: "object"
            fields:
              - { label: "Skill Name", name: "name", widget: "string" }
              - { label: "Skill Icon", name: "icon", widget: "image" }
              - { label: "Skill Cooldown", name: "cooldown", widget: "number", value_type: "int", min: 0, max: 100 }
              - label: "Skill Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Skill Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Skill Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Skill Effect Name", name: "name", widget: "string", default: "wtf" }
                      - { label: "Skill Effect Description", name: "description", widget: "text" }
                      - { label: "Skill Effect Icon", name: "icon", widget: "image" }
      - label: "Passives"
        name: "passives"
        widget: "list"
        default: []
        summary: "{{fields.passive.name}}"
        fields:
          - label: "Passive"
            name: "passive"
            widget: "object"
            fields:
              - { label: "Passive Name", name: "name", widget: "string" }
              - {
                  label: "Passive type",
                  name: "type",
                  widget: "select",
                  options: ["Normal", "Synchro"],
                  default: "Normal",
                }
              - label: "Passive Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
