backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: fromdetail/eternal-tree-db
media_folder: "src/assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Characters"
    name: "character"
    identifier_field: name
    folder: "src/game-data/characters"
    create: true
    extension: "json"
    editor:
      preview: false
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}
      - label: "Rarity"
        name: "rarity"
        widget: "select"
        options: ["SP", "SSR", "SR", "R"]
        default: "SSR"
      - label: "Skins"
        name: "skins"
        widget: "list"
        summary: "{{fields.skin.name}}"
        fields:
          - label: "Skin"
            name: "skin"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
      - label: "Tunings"
        name: "tunings"
        widget: "list"
        summary: "{{fields.tuning.name}}"
        fields:
          - label: "Tuning"
            name: "tuning"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Icon", name: "icon", widget: "image"}
              - label: "Description"
                name: "description"
                widget: "list"
                types:
                  - label: "Text"
                    name: "text"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                  - label: "Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - {label: "Name", name: "name", widget: "string", default: "wtf"}
                      - {label: "Description", name: "description", widget: "text"}
                      - {label: "Icon", name: "icon", widget: "image"}
              - {label: "Upgrade", name: "upgrade", widget: "text", required: false}


