backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: fromdetail/eternal-tree-db
media_folder: "src/assets/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Characters"
    name: "character"
    identifier_field: name
    folder: "src/characters"
    create: true
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: 'Tags', name: 'tags', widget: "hidden", default: "characters" }
      - label: "Avatar"
        name: "address"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Street Address", name: "street", widget: "string"}
          - {label: "City", name: "city", widget: "string"}
          - {label: "Postal Code", name: "post-code", widget: "string"}
