backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: fromdetail/eternal-tree-db
media_folder: "src/assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Characters"
    name: "character"
    identifier_field: name
    folder: "src/game-data/characters"
    create: true
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - label: "Element"
        name: "element"
        widget: "select"
        options: ["Fire", "Water", "Wind", "Earth", "Light", "Dark"]
        default: "Fire"
      - label: "Gacha Type"
        name: "gacha"
        widget: "select"
        options: ["Permanent", "Limited", "Event"]
        default: "Permanent"
      - label: "Role"
        name: "role"
        widget: "select"
        options: ["Attack", "Defense", "Special", "Support"]
        default: "Attack"
      - label: "Weapon type"
        name: "weapon"
        widget: "select"
        options: ["Sword", "Spear", "Staff", "Bow", "Dagger", "Axe"]
        default: "Sword"
      - label: "Rarity"
        name: "rarity"
        widget: "select"
        options: ["SP", "SSR", "SR", "R"]
        default: "SSR"
      - { label: "Attack", name: "attack", widget: "number", value_type: "int" }
      - { label: "Health", name: "health", widget: "number", value_type: "int" }
      - label: "Skins"
        name: "skins"
        widget: "list"
        summary: "{{fields.skin.name}}"
        default: []
        fields:
          - label: "Skin"
            name: "skin"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
      - label: "Bursts"
        name: "resonances"
        widget: "list"
        summary: "{{fields.resonance.name}}"
        default: []
        fields:
          - label: "Burst"
            name: "resonance"
            widget: "object"
            fields:
              - { label: "Burst Name", name: "name", widget: "string" }
              - { label: "Burst Icon", name: "icon", widget: "image" }
              - label: "Burst Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Burst Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
              - label: "Burst Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Burst Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Burst Effect Name", name: "name", widget: "string", default: "wtf" }
                      - label: "Burst Effect Description"
                        name: "description"
                        widget: "markdown"
                        modes: ["rich_text"]
                        buttons: ["bold"]
                        editor_components: []
                      - { label: "Burst Effect Icon", name: "icon", widget: "image" }
      - label: "Skills"
        name: "skills"
        widget: "list"
        default: []
        summary: "{{fields.skill.name}}"
        fields:
          - label: "Skill"
            name: "skill"
            widget: "object"
            fields:
              - { label: "Skill Name", name: "name", widget: "string" }
              - { label: "Skill Icon", name: "icon", widget: "image" }
              - { label: "Skill Cooldown", name: "cooldown", widget: "number", value_type: "int", min: 0, max: 100 }
              - label: "Skill Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Skill Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
              - label: "Skill Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Skill Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Skill Effect Name", name: "name", widget: "string", default: "wtf" }
                      - label: "Skill Effect Description"
                        name: "description"
                        widget: "markdown"
                        modes: ["rich_text"]
                        buttons: ["bold"]
                        editor_components: []
                      - { label: "Skill Effect Icon", name: "icon", widget: "image" }
      - label: "Passives"
        name: "passives"
        widget: "list"
        default: []
        summary: "{{fields.passive.name}}"
        fields:
          - label: "Passive"
            name: "passive"
            widget: "object"
            fields:
              - { label: "Passive Name", name: "name", widget: "string" }
              - {
                  label: "Passive type",
                  name: "type",
                  widget: "select",
                  options: ["Normal", "Synchro"],
                  default: "Normal",
                }
              - label: "Passive Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Passive Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
  - label: "Classes"
    name: "class"
    identifier_field: name
    folder: "src/game-data/classes"
    create: true
    extension: "json"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
      - label: "Role"
        name: "role"
        widget: "select"
        options: ["Attack", "Defense", "Special", "Support"]
        default: "Attack"
      - label: "Weapon types"
        name: "weapons"
        widget: "select"
        multiple: true
        options: ["Sword", "Spear", "Staff", "Bow", "Dagger", "Axe"]
        default: "Sword"
      - label: "Class Bonuses"
        name: "classBonus"
        widget: "markdown"
        modes: ["rich_text"]
        buttons: ["bold"]
        editor_components: []
      - label: "Shared Bonuses"
        name: "sharedBonus"
        widget: "markdown"
        modes: ["rich_text"]
        buttons: ["bold"]
        editor_components: []
      - label: "Skins"
        name: "skins"
        widget: "list"
        summary: "{{fields.skin.name}}"
        default: []
        fields:
          - label: "Skin"
            name: "skin"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
      - label: "Main Skills"
        name: "mainSkills"
        widget: "list"
        default: []
        summary: "{{fields.mainSkill.name}}"
        fields:
          - label: "Main Skill"
            name: "mainSkill"
            widget: "object"
            fields:
              - { label: "Main Skill Name", name: "name", widget: "string" }
              - { label: "Main Skill Icon", name: "icon", widget: "image" }
              - {
                  label: "Main Skill Cooldown",
                  name: "cooldown",
                  widget: "number",
                  value_type: "int",
                  min: 0,
                  max: 100,
                  required: false,
                }
              - label: "Main Skill Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Main Skill Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
              - label: "Main Skill Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Main Skill Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Main Skill Effect Name", name: "name", widget: "string", default: "wtf" }
                      - label: "Main Skill Effect Description"
                        name: "description"
                        widget: "markdown"
                        modes: ["rich_text"]
                        buttons: ["bold"]
                        editor_components: []
                      - { label: "Main Skill Effect Icon", name: "icon", widget: "image" }
      - label: "Common Skills"
        name: "commonSkills"
        widget: "list"
        default: []
        summary: "{{fields.commonSkill.name}}"
        fields:
          - label: "Common Skill"
            name: "commonSkill"
            widget: "object"
            fields:
              - { label: "Common Skill Name", name: "name", widget: "string" }
              - { label: "Common Skill Icon", name: "icon", widget: "image" }
              - {
                  label: "Common Skill Cooldown",
                  name: "cooldown",
                  widget: "number",
                  value_type: "int",
                  min: 0,
                  max: 100,
                  required: false,
                }
              - label: "Common Skill Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Common Skill Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
              - label: "Common Skill Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Common Skill Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Common Skill Effect Name", name: "name", widget: "string", default: "wtf" }
                      - label: "Common Skill Effect Description"
                        name: "description"
                        widget: "markdown"
                        modes: ["rich_text"]
                        buttons: ["bold"]
                        editor_components: []
                      - { label: "Common Skill Effect Icon", name: "icon", widget: "image" }
      - label: "Class Limited Skills"
        name: "classSkills"
        widget: "list"
        default: []
        summary: "{{fields.classSkill.name}}"
        fields:
          - label: "Class Limited Skill"
            name: "classSkill"
            widget: "object"
            fields:
              - { label: "Class Limited Skill Name", name: "name", widget: "string" }
              - { label: "Class Limited Skill Icon", name: "icon", widget: "image" }
              - {
                  label: "Class Limited Skill Cooldown",
                  name: "cooldown",
                  widget: "number",
                  value_type: "int",
                  min: 0,
                  max: 100,
                  required: false,
                }
              - label: "Class Limited Skill Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Class Limited Skill Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
              - label: "Class Limited Skill Effects"
                name: "effects"
                widget: "list"
                fields:
                  - label: "Class Limited Skill Effect"
                    name: "effect"
                    widget: "object"
                    fields:
                      - { label: "Class Limited Skill Effect Name", name: "name", widget: "string", default: "wtf" }
                      - label: "Class Limited Skill Effect Description"
                        name: "description"
                        widget: "markdown"
                        modes: ["rich_text"]
                        buttons: ["bold"]
                        editor_components: []
                      - { label: "Class Limited Skill Effect Icon", name: "icon", widget: "image" }
      - label: "Passives"
        name: "passives"
        widget: "list"
        default: []
        summary: "{{fields.passive.name}}"
        fields:
          - label: "Passive"
            name: "passive"
            widget: "object"
            fields:
              - { label: "Passive Name", name: "name", widget: "string" }
              - {
                  label: "Passive type",
                  name: "type",
                  widget: "select",
                  options: ["Normal", "Synchro"],
                  default: "Normal",
                }
              - label: "Passive Description"
                name: "description"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
              - label: "Passive Upgrade"
                name: "upgrade"
                widget: "markdown"
                modes: ["rich_text"]
                buttons: ["bold"]
                editor_components: []
                required: false
  - label: "Guide"
    name: "guide"
    folder: "src/guides"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "guide" }
      - { label: "Tags", name: "tags", widget: "hidden", default: ["guide"] }
      - { label: "Body", name: "body", widget: "markdown" }
